// Code generated by specgen from specs/RecipientMerge.tla — DO NOT EDIT.
//
// Source:     specs/RecipientMerge.tla
// Regenerate: specgen -o internal/recipientmerge -p recipientmerge specs/RecipientMerge.tla
//
// Edit the spec, not this file: change the .tla above and re-run the command.

package recipientmerge

// State mirrors the TLA+ VARIABLES.
type State struct {
	SetsEqual bool
	Wrote     bool
}

// Init returns the initial state from the TLA+ Init predicate.
func Init() State {
	s := State{
		SetsEqual: false,
		Wrote:     false,
	}
	return s
}

// CanNoteEqual is the guard for the NoteEqual action.
func (s State) CanNoteEqual() bool {
	return !(s.SetsEqual)
}

// NoteEqual applies the NoteEqual action, returning a new state.
func (s State) NoteEqual() State {
	s.SetsEqual = true
	return s
}

// CanMerge is the guard for the Merge action.
func (s State) CanMerge() bool {
	return s.SetsEqual
}

// Merge applies the Merge action, returning a new state.
func (s State) Merge() State {
	s.Wrote = true
	return s
}

// EnabledActions returns the names of actions whose guards are satisfied.
func (s State) EnabledActions() []string {
	var out []string
	if s.CanNoteEqual() {
		out = append(out, "NoteEqual")
	}
	if s.CanMerge() {
		out = append(out, "Merge")
	}
	return out
}

// --- Pure operators (no primed vars; not actions) ---

// WroteImpliesEqual is the pure TLA+ operator WroteImpliesEqual.
func (s State) WroteImpliesEqual() bool {
	return (!(s.Wrote) || (s.SetsEqual))
}

// Inv is the pure TLA+ operator Inv.
func (s State) Inv() bool {
	return (!(s.Wrote) || (s.SetsEqual))
}

// PurePredicate is a named pure decision gate (no state change).
type PurePredicate struct {
	Name  string
	Check func(State) bool
}

// PurePredicates returns every pure operator emitted for this module.
func PurePredicates() []PurePredicate {
	return []PurePredicate{
		{Name: "WroteImpliesEqual", Check: State.WroteImpliesEqual},
		{Name: "Inv", Check: State.Inv},
	}
}

// --- Trace emission for conformance checking ---

// TraceEntry is a single recorded transition for conformance validation.
// Arg and Consts are empty/nil for a named action (PATH A); for a
// Step-dispatch spec (PATH B), Arg carries the input value Step was called
// with, and Consts carries the value of every free CONSTANT parameter (e.g.
// HasSel) — without it, a replayed trace couldn't reconstruct what Step
// actually saw whenever a free var varies between calls.
type TraceEntry struct {
	Action string          `json:"action"`
	Arg    string          `json:"arg,omitempty"`
	Args   []string        `json:"args,omitempty"`
	Consts map[string]bool `json:"consts,omitempty"`
	Pre    State           `json:"pre"`
	Post   State           `json:"post"`
}

// ApplyAction dispatches a named action, returning the new state.
// Panics on unknown action names.
func (s State) ApplyAction(name string) State {
	switch name {
	case "NoteEqual":
		return s.NoteEqual()
	case "Merge":
		return s.Merge()
	default:
		panic("unknown action: " + name)
	}
}

// Trace records a transition: applies the action and returns
// both the trace entry and the new state.
func (s State) Trace(action string) (TraceEntry, State) {
	pre := s
	post := s.ApplyAction(action)
	return TraceEntry{
		Action: action,
		Pre:    pre,
		Post:   post,
	}, post
}
