// Code generated by specgen from specs/VaultAdmit.tla — DO NOT EDIT.
//
// Source:     specs/VaultAdmit.tla
// Regenerate: specgen -o internal/vaultadmit -p vaultadmit specs/VaultAdmit.tla
//
// Edit the spec, not this file: change the .tla above and re-run the command.

package vaultadmit

// State mirrors the TLA+ VARIABLES.
type State struct {
	Eve      bool
	Accepted bool
	MacOk    bool
	Wrote    bool
}

// Init returns the initial state from the TLA+ Init predicate.
func Init() State {
	s := State{
		Eve:      false,
		Accepted: true,
		MacOk:    true,
		Wrote:    false,
	}
	return s
}

// CanForge is the guard for the Forge action.
func (s State) CanForge() bool {
	return (s.MacOk && s.Accepted)
}

// Forge applies the Forge action, returning a new state.
func (s State) Forge() State {
	s.Eve = true
	s.Accepted = false
	s.Wrote = false
	return s
}

// CanTamper is the guard for the Tamper action.
func (s State) CanTamper() bool {
	return s.MacOk
}

// Tamper applies the Tamper action, returning a new state.
func (s State) Tamper() State {
	s.MacOk = false
	s.Wrote = false
	return s
}

// CanAccept is the guard for the Accept action.
func (s State) CanAccept() bool {
	return !(s.Accepted)
}

// Accept applies the Accept action, returning a new state.
func (s State) Accept() State {
	s.Accepted = true
	return s
}

// CanSet is the guard for the Set action.
func (s State) CanSet() bool {
	return (s.MacOk && s.Accepted)
}

// Set applies the Set action, returning a new state.
func (s State) Set() State {
	s.Wrote = true
	return s
}

// EnabledActions returns the names of actions whose guards are satisfied.
func (s State) EnabledActions() []string {
	var out []string
	if s.CanForge() {
		out = append(out, "Forge")
	}
	if s.CanTamper() {
		out = append(out, "Tamper")
	}
	if s.CanAccept() {
		out = append(out, "Accept")
	}
	if s.CanSet() {
		out = append(out, "Set")
	}
	return out
}

// --- Pure operators (no primed vars; not actions) ---

// WroteImpliesAdmitted is the pure TLA+ operator WroteImpliesAdmitted.
func (s State) WroteImpliesAdmitted() bool {
	return (!(s.Wrote) || (s.MacOk && s.Accepted))
}

// Inv is the pure TLA+ operator Inv.
func (s State) Inv() bool {
	return (!(s.Wrote) || (s.MacOk && s.Accepted))
}

// PurePredicate is a named pure decision gate (no state change).
type PurePredicate struct {
	Name  string
	Check func(State) bool
}

// PurePredicates returns every pure operator emitted for this module.
func PurePredicates() []PurePredicate {
	return []PurePredicate{
		{Name: "WroteImpliesAdmitted", Check: State.WroteImpliesAdmitted},
		{Name: "Inv", Check: State.Inv},
	}
}

// --- Trace emission for conformance checking ---

// TraceEntry is a single recorded transition for conformance validation.
// Arg and Consts are empty/nil for a named action (PATH A); for a
// Step-dispatch spec (PATH B), Arg carries the input value Step was called
// with, and Consts carries the value of every free CONSTANT parameter (e.g.
// HasSel) — without it, a replayed trace couldn't reconstruct what Step
// actually saw whenever a free var varies between calls.
type TraceEntry struct {
	Action string          `json:"action"`
	Arg    string          `json:"arg,omitempty"`
	Args   []string        `json:"args,omitempty"`
	Consts map[string]bool `json:"consts,omitempty"`
	Pre    State           `json:"pre"`
	Post   State           `json:"post"`
}

// ApplyAction dispatches a named action, returning the new state.
// Panics on unknown action names.
func (s State) ApplyAction(name string) State {
	switch name {
	case "Forge":
		return s.Forge()
	case "Tamper":
		return s.Tamper()
	case "Accept":
		return s.Accept()
	case "Set":
		return s.Set()
	default:
		panic("unknown action: " + name)
	}
}

// Trace records a transition: applies the action and returns
// both the trace entry and the new state.
func (s State) Trace(action string) (TraceEntry, State) {
	pre := s
	post := s.ApplyAction(action)
	return TraceEntry{
		Action: action,
		Pre:    pre,
		Post:   post,
	}, post
}
