// Code generated by specgen — DO NOT EDIT.

package vaultadmit

import (
	"fmt"
	"testing"
)

func TestInit(t *testing.T) {
	s := Init()
	if s.Eve != bool(false) {
		t.Errorf("Eve = %v, want %v", s.Eve, bool(false))
	}
	if s.Accepted != bool(true) {
		t.Errorf("Accepted = %v, want %v", s.Accepted, bool(true))
	}
	if s.MacOk != bool(true) {
		t.Errorf("MacOk = %v, want %v", s.MacOk, bool(true))
	}
	if s.Wrote != bool(false) {
		t.Errorf("Wrote = %v, want %v", s.Wrote, bool(false))
	}
}

// TestBFSReachability walks the state space from Init, applying every
// enabled action. Verifies no transition panics and all states are reachable.
func TestBFSReachability(t *testing.T) {
	seen := map[string]bool{}
	queue := []State{Init()}
	maxStates := 10000

	for len(queue) > 0 && len(seen) < maxStates {
		s := queue[0]
		queue = queue[1:]
		key := fmt.Sprintf("%+v", s)
		if seen[key] {
			continue
		}
		seen[key] = true

		for _, action := range s.EnabledActions() {
			next := s.ApplyAction(action)
			queue = append(queue, next)
		}
	}

	if len(seen) == 0 {
		t.Fatal("no reachable states")
	}
	t.Logf("explored %d reachable states", len(seen))
}

// TestPurePredicates evaluates every pure operator on Init.
// Ensures the registry is non-empty and methods do not panic.
func TestPurePredicates(t *testing.T) {
	s := Init()
	preds := PurePredicates()
	if len(preds) == 0 {
		t.Fatal("PurePredicates empty")
	}
	for _, p := range preds {
		t.Run(p.Name, func(t *testing.T) {
			_ = p.Check(s) // must not panic
		})
	}
}
